// <auto-generated />
using Alis_Veris_Plus.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alis_Veris_Plus.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241009170026_SeedDataUpdate")]
    partial class SeedDataUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Alis_Veris_Plus.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Açıklama 1",
                            ImageUrl = "https://example.com/image1.jpg",
                            Name = "Ürün 1",
                            Price = 100.00m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Açıklama 2",
                            ImageUrl = "https://example.com/image2.jpg",
                            Name = "Ürün 2",
                            Price = 200.00m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Açıklama 3",
                            ImageUrl = "https://example.com/image3.jpg",
                            Name = "Ürün 3",
                            Price = 300.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
